name: SpiderFoot Acceptance Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Acceptance Test dependencies
        run: pip3 install -r test/acceptance/requirements.txt

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Start SpiderFoot container
        run: |
          docker run -d -p 5001:5001 ghcr.io/poppopjmp/spiderfoot:v5.0.1

      - name: Wait for SpiderFoot to start
        run: |
          timeout 60 bash -c 'until curl --output /dev/null --silent --head --fail http://127.0.0.1:5001; do printf "."; sleep 1; done'
          echo "SpiderFoot is up!"

      - name: Install chromedriver
        run: |
          wget "https://chromedriver.storage.googleapis.com/133.0.6943.141/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Robot Framework tests
        run: |
          cd test/acceptance
          robot --variable BROWSER:Chrome --outputdir results scan.robot

      - name: Stop SpiderFoot container
        run: docker stop $(docker ps -q --filter ancestor=ghcr.io/poppopjmp/spiderfoot)

      - name: Upload Robot Framework results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: test/acceptance/results
