name: Code Quality

on:
  push:
    branches: [master, v5.0.3-dev]
  pull_request:
    branches: [master, v5.0.3-dev]
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        language: ["python"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install jscpd
        run: npm install -g jscpd

      - name: Run jscpd
        run: jscpd --min-tokens 50 --reporters console .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install docformatter, black, and autopep8
        run: |
          pip install autopep8

      - name: Run autopep8
        run: autopep8 --in-place --recursive .

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git commit -m "Auto-format docstrings with docformatter" || echo "No changes to commit"
          git push
  
  docformatter:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing changes
    
    steps:
    - uses: actions/checkout@v3
      with:
        # Important: fetch all history for git commits
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docformatter
        
    - name: Check if any docstring formatting issues exist
      id: check-formatting
      continue-on-error: true
      run: |
        docformatter --in-place --recursive .
        echo "HAS_ISSUES=$?" >> $GITHUB_ENV
        
       
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -A
        git commit -m "Auto-format docstrings with docformatter" || echo "No changes to commit"
        git push
