name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Lint Dockerfile with Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: error 
        
    - name: Login to GitHub Container Registry (if needed)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}
    - name: Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}:${{ github.sha }}'
        ignore-unfixed: 'true'
          
    - name: Run container tests
      run: |
        docker run --rm ghcr.io/${{ github.repository }}:${{ github.sha }} sf.py -h
        docker run --rm ghcr.io/${{ github.repository }}:${{ github.sha }} sf.py --version

  build-react-web-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Lint Dockerfile with Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: react-web-interface/Dockerfile
        failure-threshold: error

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push React web app Docker image
      id: docker_build_react
      uses: docker/build-push-action@v5
      with:
        context: react-web-interface
        file: react-web-interface/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:react-latest
          ghcr.io/${{ github.repository }}:react-${{ github.sha }}

    - name: Run container tests for React web app
      run: |
        docker run --rm ghcr.io/${{ github.repository }}:react-${{ github.sha }} npm run test
