name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag spiderfoot:$(date +%s)
- name: Build the Docker image Full
      run: docker build . --file Dockerfile.full --tag spiderfoot-full:$(date +%s)
