name: Code Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install jscpd
        run: npm install -g jscpd

      - name: Run jscpd
        run: jscpd --min-tokens 50 --reporters console .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install docformatter, black, and autopep8
        run: |
          pip install autopep8 docformatter

      - name: Run autopep8
        run: |
          autopep8 --in-place --recursive .
          docformatter --in-place --recursive .

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub PEP8 Action'
          git config --global user.email 'actions@github.com'
          git add -A
          git commit -m "Auto-format docstrings with docformatter" || echo "No changes to commit"
          git push
  
